apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pyapp
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pyapp
  targetCPUUtilizationPercentage: 60